package com.xact.sy195.model;
import jakarta.persistence.*;
import lombok.Data;
import java.math.BigDecimal;
import java.time.LocalDate;

@Data @Entity @Table(name = "cl01_mast")
public class Cl01Mast {
    @Id @Column(name = "cl_code", length = 8)   private String clCode;
    @Column(name = "cl_name", length = 40)       private String clName;
    @Column(name = "status", length = 1)         private String status;
    @Column(name = "master_acct", length = 1)    private String masterAcct;
    @Column(name = "linked_acct", length = 8)    private String linkedAcct;
    @Column(name = "tel_1", length = 22)         private String tel1;
    @Column(name = "tel_2", length = 22)         private String tel2;
    @Column(name = "fax_1", length = 22)         private String fax1;
    @Column(name = "fax_2", length = 22)         private String fax2;
    @Column(name = "email", length = 80)         private String email;
    @Column(name = "po_email", length = 80)      private String poEmail;
    @Column(name = "cr_email", length = 80)      private String crEmail;
    @Column(name = "rm_email", length = 80)      private String rmEmail;
    @Column(name = "controlled_by", length = 10) private String controlledBy;
    @Column(name = "contact", length = 29)       private String contact;
    @Column(name = "supp_acct_code", length = 15) private String suppAcctCode;
    @Column(name = "vat_no", length = 12)        private String vatNo;
    @Column(name = "co_reg", length = 17)        private String coReg;
    @Column(name = "post_add_1", length = 30)    private String postAdd1;
    @Column(name = "post_add_2", length = 30)    private String postAdd2;
    @Column(name = "post_add_3", length = 30)    private String postAdd3;
    @Column(name = "post_add_4", length = 10)    private String postAdd4;
    @Column(name = "post_code", length = 4)      private String postCode;
    @Column(name = "phy_add_1", length = 30)     private String phyAdd1;
    @Column(name = "phy_add_2", length = 30)     private String phyAdd2;
    @Column(name = "phy_add_3", length = 30)     private String phyAdd3;
    @Column(name = "phy_add_4", length = 10)     private String phyAdd4;
    @Column(name = "delivery_by", length = 4)    private String deliveryBy;
    @Column(name = "del_area", length = 5)       private String delArea;
    @Column(name = "cl_cat", length = 5)         private String clCat;
    @Column(name = "bee_rating")                 private Integer beeRating = 0;
    @Column(name = "bee_expiry_date")            private LocalDate beeExpiryDate;
    @Column(name = "opened_date")                private LocalDate openedDate;
    @Column(name = "amend_po_grn_add", length = 1) private String amendPoGrnAdd;
    @Column(name = "last_inv_date")              private LocalDate lastInvDate;
    @Column(name = "last_pay_date")              private LocalDate lastPayDate;
    @Column(name = "terms")                      private Integer terms = 0;
    @Column(name = "terms_from", length = 1)     private String termsFrom;
    @Column(name = "sett_disc", precision = 7, scale = 2) private BigDecimal settDisc = BigDecimal.ZERO;
    @Column(name = "cred_limit", precision = 13, scale = 0) private BigDecimal credLimit = BigDecimal.ZERO;
    @Column(name = "block_recons", length = 1)   private String blockRecons;
    @Column(name = "block_internal_rebate", length = 1) private String blockInternalRebate;
    @Column(name = "incl_in_cb_auto_tag", length = 1) private String inclInCbAutoTag = "Y";
    @Column(name = "ic_acct", length = 1)        private String icAcct = "N";
    @Column(name = "block_acct", length = 1)     private String blockAcct;
    @Column(name = "import_acct", length = 1)    private String importAcct;
    @Column(name = "track_by_foreign_currency", length = 1) private String trackByForeignCurrency;
    @Column(name = "foreign_currency", length = 10) private String foreignCurrency;
    @Column(name = "bank_name", length = 20)     private String bankName;
    @Column(name = "bank_code", length = 15)     private String bankCode;
    @Column(name = "bank_branch_name", length = 20) private String bankBranchName;
    @Column(name = "bank_branch_code", length = 15) private String bankBranchCode;
    @Column(name = "bank_acct_type", length = 2) private String bankAcctType;
    @Column(name = "bank_acct_no", length = 35)  private String bankAcctNo;
    @Column(name = "approval_pending", length = 1) private String approvalPending;
    @Column(name = "balance", precision = 13, scale = 2) private BigDecimal balance = BigDecimal.ZERO;
    @Column(name = "balance_forex", precision = 13, scale = 2) private BigDecimal balanceForex = BigDecimal.ZERO;
    @Column(name = "age_cur", precision = 13, scale = 2) private BigDecimal ageCur = BigDecimal.ZERO;
    @Column(name = "age_30", precision = 13, scale = 2) private BigDecimal age30 = BigDecimal.ZERO;
    @Column(name = "age_60", precision = 13, scale = 2) private BigDecimal age60 = BigDecimal.ZERO;
    @Column(name = "age_90", precision = 13, scale = 2) private BigDecimal age90 = BigDecimal.ZERO;
    @Column(name = "age_120", precision = 13, scale = 2) private BigDecimal age120 = BigDecimal.ZERO;
    @Column(name = "age_120_plus", precision = 13, scale = 2) private BigDecimal age120Plus = BigDecimal.ZERO;
    @Column(name = "po_out", precision = 13, scale = 2) private BigDecimal poOut = BigDecimal.ZERO;
    @Column(name = "grn_out", precision = 13, scale = 2) private BigDecimal grnOut = BigDecimal.ZERO;
    @Column(name = "pay_allocated", precision = 13, scale = 2) private BigDecimal payAllocated = BigDecimal.ZERO;
    @Column(name = "recon_stat_bal", precision = 13, scale = 2) private BigDecimal reconStatBal = BigDecimal.ZERO;
    @Column(name = "recon_stat_date")            private LocalDate reconStatDate;
    @Column(name = "recon_pay_date")             private LocalDate reconPayDate;
    @Column(name = "last_cl30_row_id")           private Integer lastCl30RowId = 0;
    @Column(name = "last_cl33_row_id")           private Integer lastCl33RowId = 0;
}
