package com.xact.sy195.model;
import jakarta.persistence.*;
import lombok.Data;
import java.math.BigDecimal;
import java.time.LocalDate;

@Data @Entity @Table(name = "st01_mast")
public class St01Mast {
    @Id @Column(name = "stk_code", length = 16) private String stkCode;
    @Column(name = "status", length = 1)          private String status;
    @Column(name = "replen_status", length = 1)   private String replenStatus;
    @Column(name = "master_acct", length = 1)     private String masterAcct;
    @Column(name = "linked_to", length = 16)      private String linkedTo;
    @Column(name = "web_enabled", length = 1)     private String webEnabled;
    @Column(name = "retail_enabled", length = 1)  private String retailEnabled;
    @Column(name = "trade_in_item", length = 1)   private String tradeInItem;
    @Column(name = "import_item", length = 1)     private String importItem;
    @Column(name = "track_expiry_date", length = 1) private String trackExpiryDate = "N";
    @Column(name = "api_enabled", length = 1)     private String apiEnabled = "N";
    @Column(name = "api_prod_code", length = 13)  private String apiProdCode;
    @Column(name = "reverse_qty_sign", length = 1) private String reverseQtySign = "N";
    @Column(name = "reverse_type", length = 1)    private String reverseType;
    @Column(name = "qty_decimal_input", length = 1) private String qtyDecimalInput;
    @Column(name = "scale_item", length = 1)      private String scaleItem;
    @Column(name = "scale_type", length = 1)      private String scaleType;
    @Column(name = "scale_shelf_life")            private Integer scaleShelfLife;
    @Column(name = "create_date")                 private LocalDate createDate;
    @Column(name = "desc_1", length = 40)         private String desc1;
    @Column(name = "desc_2", length = 40)         private String desc2;
    @Column(name = "desc_3", length = 40)         private String desc3;
    @Column(name = "desc_4", length = 40)         private String desc4;
    @Column(name = "desc_5", length = 40)         private String desc5;
    @Column(name = "desc_6", length = 40)         private String desc6;
    @Column(name = "barcode", length = 16)        private String barcode;
    @Column(name = "keep_bal", length = 1)        private String keepBal;
    @Column(name = "import_duty_item", length = 1) private String importDutyItem;
    @Column(name = "stk_grp", length = 5)         private String stkGrp;
    @Column(name = "list_gp_cat", length = 1)     private String listGpCat;
    @Column(name = "serial_track", length = 1)    private String serialTrack;
    @Column(name = "auto_gen_serial", length = 1) private String autoGenSerial;
    @Column(name = "serial_pack", length = 4)     private String serialPack;
    @Column(name = "track_sfd", length = 1)       private String trackSfd = "N";
    @Column(name = "price_list_item", length = 1) private String priceListItem;
    @Column(name = "keep_tran", length = 1)       private String keepTran;
    @Column(name = "default_bom_type", length = 3) private String defaultBomType;
    @Column(name = "gl_grp")                      private Integer glGrp = 0;
    @Column(name = "uom", length = 5)             private String uom;
    @Column(name = "unit_qty", precision = 11, scale = 3) private BigDecimal unitQty = BigDecimal.ZERO;
    @Column(name = "mass", precision = 11, scale = 3) private BigDecimal mass = BigDecimal.ZERO;
    @Column(name = "warn_lvl_1")                  private Integer warnLvl1 = 0;
    @Column(name = "warn_lvl_2")                  private Integer warnLvl2 = 0;
    @Column(name = "lead_time", precision = 5, scale = 2) private BigDecimal leadTime = BigDecimal.ZERO;
    @Column(name = "line_type", length = 1)       private String lineType;
    @Column(name = "re_order")                    private Integer reOrder = 0;
    @Column(name = "re_order_perc")               private Integer reOrderPerc = 0;
    @Column(name = "qc_enabled", length = 1)      private String qcEnabled;
    @Column(name = "qc_based_on", length = 1)     private String qcBasedOn;
    @Column(name = "qc_qty", precision = 11, scale = 3) private BigDecimal qcQty = BigDecimal.ZERO;
    @Column(name = "qc_perc", precision = 7, scale = 2) private BigDecimal qcPerc = BigDecimal.ZERO;
    @Column(name = "qc_instructions", length = 255) private String qcInstructions;
    @Column(name = "hs_code", length = 13)        private String hsCode;
    @Column(name = "duty_tariff_code", length = 16) private String dutyTariffCode;
    @Column(name = "clearing_agent_code", length = 8) private String clearingAgentCode;
    @Column(name = "import_currency", length = 10) private String importCurrency;
    @Column(name = "levy_code", length = 6)       private String levyCode;
    @Column(name = "vat_ind", length = 1)         private String vatInd;
    @Column(name = "enter_cost", length = 1)      private String enterCost;
    @Column(name = "ovrd_desc", length = 4)       private String ovrdDesc;
    @Column(name = "auto_price", length = 1)      private String autoPrice;
    @Column(name = "last_st30_row_id")            private Integer lastSt30RowId = 0;
    @Column(name = "last_st30i_row_id")           private Integer lastSt30iRowId = 0;
    @Column(name = "last_st33_row_id")            private Integer lastSt33RowId = 0;
}
