-- XactERP sy195 schema
-- Matches xactdev_db production schema exactly
-- Run once: psql -U postgres -d xactdev -f schema.sql

-- ── Core master tables (matching real xactdev_db schema) ──────────────────────

CREATE TABLE IF NOT EXISTS public.dl01_mast (
    dl_code                     character varying(8)   NOT NULL,
    dl_name                     character varying(40),
    status                      character varying(1),
    master_acct                 character varying(1),
    address_only_acct           character varying(1),
    linked_acct                 character varying(8),
    loc                         character varying(3),
    filing_code                 character varying(8),
    tel_1                       character varying(22),
    tel_2                       character varying(22),
    fax_1                       character varying(22),
    fax_2                       character varying(22),
    contact                     character varying(29),
    popi_conf                   character varying(1)   DEFAULT 'N',
    controlled_by               character varying(10),
    cust_acct_code              character varying(8),
    co_reg                      character varying(17),
    vat_no                      character varying(12),
    post_add_1                  character varying(30),
    post_add_2                  character varying(30),
    post_add_3                  character varying(30),
    post_add_4                  character varying(10),
    post_code                   character varying(4),
    phy_add_1                   character varying(30),
    phy_add_2                   character varying(30),
    phy_add_3                   character varying(30),
    phy_add_4                   character varying(20),
    delivery_by                 character varying(4),
    del_area                    character varying(5),
    dl_cat                      character varying(5),
    sync_dl_cat_disc            character varying(1)   DEFAULT 'N',
    region                      character varying(5),
    rep_code                    character varying(5),
    mkt_rep                     character varying(5),
    class                       character varying(3),
    target_based_on             character varying(1),
    send_stmt                   character varying(1),
    bee_rating                  integer                DEFAULT 0,
    bee_expiry_date             date,
    export_acct                 character varying(1),
    track_by_foreign_currency   character varying(1),
    foreign_currency            character varying(10),
    opened_date                 date,
    so_pick_stk                 character varying(1),
    inv_type                    character varying(1),
    inv_incl                    character varying(1),
    amend_so_inv_add            character varying(1),
    auto_cession_of_inv         character varying(1),
    auto_email_inv_on_prt       character varying(1)   DEFAULT 'N',
    enable_rounding             character varying(1),
    incl_in_cb_auto_tag         character varying(1)   DEFAULT 'Y',
    cr_limit_currency           character varying(1)   DEFAULT 'L',
    cr_status                   character varying(4),
    terms                       integer                DEFAULT 0,
    terms_from                  character varying(1),
    sett_disc                   numeric(7,2)           DEFAULT 0,
    max_cr_limit                numeric(13,2)          DEFAULT 0,
    max_cr_limit_forex          numeric(13,2)          DEFAULT 0,
    cr_limit                    numeric(13,2)          DEFAULT 0,
    cr_limit_forex              numeric(13,2)          DEFAULT 0,
    temp_cr_limit               character varying(1),
    temp_cr_valid_until         date,
    org_cr_limit                numeric(13,2)          DEFAULT 0,
    org_cr_limit_forex          numeric(13,2)          DEFAULT 0,
    deposit_held                numeric(13,2)          DEFAULT 0,
    deposit_held_forex          numeric(13,2)          DEFAULT 0,
    debtor_insurance            numeric(13,2)          DEFAULT 0,
    debtor_insurance_forex      numeric(13,2)          DEFAULT 0,
    enable_auto_hold            character varying(1),
    charge_interest             character varying(1),
    surety                      character varying(1),
    legal_action                character varying(1),
    comment                     character varying(400),
    email                       character varying(80),
    qt_email                    character varying(80),
    inv_email                   character varying(80),
    stmt_email                  character varying(80),
    balance                     numeric(13,2)          DEFAULT 0,
    balance_forex               numeric(13,2)          DEFAULT 0,
    age_cur                     numeric(13,2)          DEFAULT 0,
    age_cur_forex               numeric(13,2)          DEFAULT 0,
    age_30                      numeric(13,2)          DEFAULT 0,
    age_30_forex                numeric(13,2)          DEFAULT 0,
    age_60                      numeric(13,2)          DEFAULT 0,
    age_60_forex                numeric(13,2)          DEFAULT 0,
    age_90                      numeric(13,2)          DEFAULT 0,
    age_90_forex                numeric(13,2)          DEFAULT 0,
    age_120                     numeric(13,2)          DEFAULT 0,
    age_120_forex               numeric(13,2)          DEFAULT 0,
    age_120_plus                numeric(13,2)          DEFAULT 0,
    age_120_plus_forex          numeric(13,2)          DEFAULT 0,
    so_bo_out                   numeric(13,2)          DEFAULT 0,
    so_bo_out_forex             numeric(13,2)          DEFAULT 0,
    so_stk_out                  numeric(13,2)          DEFAULT 0,
    so_stk_out_forex            numeric(13,2)          DEFAULT 0,
    daybook_inv_tot             numeric(13,2)          DEFAULT 0,
    daybook_inv_tot_forex       numeric(13,2)          DEFAULT 0,
    ic_acct                     character varying(1)   DEFAULT 'N',
    ic_min_gp_perc              numeric(7,2)           DEFAULT 0,
    auto_hold_active            character varying(1),
    last_inv_date               date,
    last_pay_date               date,
    last_dl30_row_id            integer                DEFAULT 0,
    custom_field_1              character varying(20),
    custom_field_2              character varying(20),
    custom_field_3              character varying(20),
    custom_field_4              character varying(20),
    custom_field_5              character varying(20),
    custom_field_6              character varying(20),
    custom_field_7              character varying(20),
    custom_field_8              character varying(20),
    custom_field_9              character varying(20),
    custom_field_10             character varying(20),
    CONSTRAINT dl01_pk PRIMARY KEY (dl_code)
);
CREATE INDEX IF NOT EXISTS dl01_linked_code_dl_code ON public.dl01_mast USING btree (linked_acct DESC, dl_code DESC);

CREATE TABLE IF NOT EXISTS public.st01_mast (
    stk_code                    character varying(16)  NOT NULL,
    status                      character varying(1),
    replen_status               character varying(1),
    master_acct                 character varying(1),
    linked_to                   character varying(16),
    web_enabled                 character varying(1),
    retail_enabled              character varying(1),
    trade_in_item               character varying(1),
    import_item                 character varying(1),
    track_expiry_date           character varying(1)   DEFAULT 'N',
    api_enabled                 character varying(1)   DEFAULT 'N',
    api_prod_code               character varying(13),
    reverse_qty_sign            character varying(1)   DEFAULT 'N',
    reverse_type                character varying(1),
    qty_decimal_input           character varying(1),
    scale_item                  character varying(1),
    scale_type                  character varying(1),
    scale_shelf_life            integer,
    create_date                 date,
    desc_1                      character varying(40),
    desc_2                      character varying(40),
    desc_3                      character varying(40),
    desc_4                      character varying(40),
    desc_5                      character varying(40),
    desc_6                      character varying(40),
    barcode                     character varying(16),
    keep_bal                    character varying(1),
    import_duty_item            character varying(1),
    stk_grp                     character varying(5),
    list_gp_cat                 character varying(1),
    serial_track                character varying(1),
    auto_gen_serial             character varying(1),
    serial_pack                 character varying(4),
    track_sfd                   character varying(1)   DEFAULT 'N',
    price_list_item             character varying(1),
    keep_tran                   character varying(1),
    default_bom_type            character varying(3),
    gl_grp                      integer                DEFAULT 0,
    uom                         character varying(5),
    unit_qty                    numeric(11,3)          DEFAULT 0,
    mass                        numeric(11,3)          DEFAULT 0,
    warn_lvl_1                  integer                DEFAULT 0,
    warn_lvl_2                  integer                DEFAULT 0,
    lead_time                   numeric(5,2)           DEFAULT 0,
    line_type                   character varying(1),
    re_order                    integer                DEFAULT 0,
    re_order_perc               integer                DEFAULT 0,
    qc_enabled                  character varying(1),
    qc_based_on                 character varying(1),
    qc_qty                      numeric(11,3)          DEFAULT 0,
    qc_perc                     numeric(7,2)           DEFAULT 0,
    qc_instructions             character varying(255),
    hs_code                     character varying(13),
    duty_tariff_code            character varying(16),
    clearing_agent_code         character varying(8),
    import_currency             character varying(10),
    levy_code                   character varying(6),
    vat_ind                     character varying(1),
    enter_cost                  character varying(1),
    ovrd_desc                   character varying(4),
    auto_price                  character varying(1),
    last_st30_row_id            integer                DEFAULT 0,
    last_st30i_row_id           integer                DEFAULT 0,
    last_st33_row_id            integer                DEFAULT 0,
    CONSTRAINT st01_pk PRIMARY KEY (stk_code)
);
CREATE INDEX IF NOT EXISTS st01_grp_code ON public.st01_mast USING btree (stk_grp, stk_code);

CREATE TABLE IF NOT EXISTS public.cl01_mast (
    cl_code                     character varying(8)   NOT NULL,
    cl_name                     character varying(40),
    status                      character varying(1),
    master_acct                 character varying(1),
    linked_acct                 character varying(8),
    tel_1                       character varying(22),
    tel_2                       character varying(22),
    fax_1                       character varying(22),
    fax_2                       character varying(22),
    email                       character varying(80),
    po_email                    character varying(80),
    cr_email                    character varying(80),
    rm_email                    character varying(80),
    controlled_by               character varying(10),
    contact                     character varying(29),
    supp_acct_code              character varying(15),
    vat_no                      character varying(12),
    co_reg                      character varying(17),
    post_add_1                  character varying(30),
    post_add_2                  character varying(30),
    post_add_3                  character varying(30),
    post_add_4                  character varying(10),
    post_code                   character varying(4),
    phy_add_1                   character varying(30),
    phy_add_2                   character varying(30),
    phy_add_3                   character varying(30),
    phy_add_4                   character varying(10),
    delivery_by                 character varying(4),
    del_area                    character varying(5),
    cl_cat                      character varying(5),
    bee_rating                  integer                DEFAULT 0,
    bee_expiry_date             date,
    opened_date                 date,
    amend_po_grn_add            character varying(1),
    last_inv_date               date,
    last_pay_date               date,
    terms                       integer                DEFAULT 0,
    terms_from                  character varying(1),
    sett_disc                   numeric(7,2)           DEFAULT 0,
    cred_limit                  numeric(13,0)          DEFAULT 0,
    block_recons                character varying(1),
    block_internal_rebate       character varying(1),
    incl_in_cb_auto_tag         character varying(1)   DEFAULT 'Y',
    ic_acct                     character varying(1)   DEFAULT 'N',
    block_acct                  character varying(1),
    import_acct                 character varying(1),
    track_by_foreign_currency   character varying(1),
    foreign_currency            character varying(10),
    bank_name                   character varying(20),
    bank_code                   character varying(15),
    bank_branch_name            character varying(20),
    bank_branch_code            character varying(15),
    bank_acct_type              character varying(2),
    bank_acct_no                character varying(35),
    approval_pending            character varying(1),
    balance                     numeric(13,2)          DEFAULT 0,
    balance_forex               numeric(13,2)          DEFAULT 0,
    age_cur                     numeric(13,2)          DEFAULT 0,
    age_cur_forex               numeric(13,2)          DEFAULT 0,
    age_30                      numeric(13,2)          DEFAULT 0,
    age_30_forex                numeric(13,2)          DEFAULT 0,
    age_60                      numeric(13,2)          DEFAULT 0,
    age_60_forex                numeric(13,2)          DEFAULT 0,
    age_90                      numeric(13,2)          DEFAULT 0,
    age_90_forex                numeric(13,2)          DEFAULT 0,
    age_120                     numeric(13,2)          DEFAULT 0,
    age_120_forex               numeric(13,2)          DEFAULT 0,
    age_120_plus                numeric(13,2)          DEFAULT 0,
    age_120_plus_forex          numeric(13,2)          DEFAULT 0,
    po_out                      numeric(13,2)          DEFAULT 0,
    po_out_forex                numeric(13,2)          DEFAULT 0,
    grn_out                     numeric(13,2)          DEFAULT 0,
    grn_out_forex               numeric(13,2)          DEFAULT 0,
    pay_allocated               numeric(13,2)          DEFAULT 0,
    pay_allocated_forex         numeric(13,2)          DEFAULT 0,
    recon_stat_bal              numeric(13,2)          DEFAULT 0,
    recon_stat_date             date,
    recon_pay_date              date,
    last_cl30_row_id            integer                DEFAULT 0,
    last_cl33_row_id            integer                DEFAULT 0,
    CONSTRAINT cl01_pk PRIMARY KEY (cl_code)
);

CREATE TABLE IF NOT EXISTS public.gl01_mast (
    gl_code                     character varying(8)   NOT NULL,
    descr                       character varying(40),
    status                      character varying(1),
    acct_type                   character varying(1),
    post                        character varying(1),
    control                     character varying(8),
    detail_trans                character varying(1),
    loc_anal                    character varying(1),
    budget                      character varying(1),
    budget_based_on             character varying(1),
    note_no                     integer                DEFAULT 0,
    interface_acct              character varying(1),
    block_posting               character varying(1),
    last_gl30_row_id            integer                DEFAULT 0,
    CONSTRAINT gl01_pk PRIMARY KEY (gl_code)
);

CREATE TABLE IF NOT EXISTS public.gl02_loc_mast (
    loc                         character varying(3)   NOT NULL,
    whs                         character varying(3)   NOT NULL,
    default_del_loc             character varying(3),
    default_del_whs             character varying(3),
    link_to_dc_loc              character varying(3),
    link_to_dc_whs              character varying(3),
    status                      character varying(1),
    loc_name                    character varying(30),
    region                      character varying(3),
    use_loc_add                 character varying(1),
    add_1                       character varying(35),
    add_2                       character varying(35),
    add_3                       character varying(35),
    add_4                       character varying(35),
    post_add_1                  character varying(35),
    post_add_2                  character varying(35),
    post_add_3                  character varying(35),
    post_add_4                  character varying(35),
    area_dialcode_international integer,
    area_dialcode_local         integer,
    tel_no                      character varying(15),
    fax_no                      character varying(15),
    branch_manager              character varying(10),
    stk_loc                     character varying(1),
    sales_whs                   character varying(1),
    sales_pick_stk_from         character varying(1),
    pur_whs                     character varying(1),
    replen_whs                  character varying(1),
    dc_whs                      character varying(1),
    crossd_whs                  character varying(1),
    bo_whs                      character varying(1),
    ibt_whs                     character varying(1),
    ibt_pick_stk_from           character varying(1),
    grv_stk_from                character varying(1),
    dispatch_whs                character varying(1),
    mrp_whs                     character varying(1),
    default_del_area            character varying(4),
    bin_qty_tracking            character varying(1),
    allow_del_loc_chg           character varying(1),
    prt_pod_barcodes            character varying(1),
    loc_inv_prt                 integer,
    pod_barcode_prt             integer,
    serial_prt                  integer,
    staging_loc_prt             integer,
    stores_dispatch_prt         integer,
    stores_receive_prt          integer,
    inv_cod_acct_thru_pos       character varying(1),
    pos_tender_type             character varying(1),
    pos_cashup_type             character varying(1),
    pos_dl_cash_sale_acct       character varying(8),
    pos_dl_collection_acct      character varying(8),
    web_enabled                 character varying(1),
    click_collect_enabled       character varying(1),
    web_sales_acct              character varying(8),
    inv_type                    character varying(1),
    inv_page_1                  character varying(1),
    inv_page_2                  character varying(1),
    inv_page_3                  character varying(1),
    inv_page_4                  character varying(1),
    CONSTRAINT gl02_pk PRIMARY KEY (loc, whs)
);
CREATE INDEX IF NOT EXISTS gl02_stk_loc ON public.gl02_loc_mast USING btree (stk_loc);

-- ── System tables ─────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.sy02l_user_loc (
    user_name                   character varying(10)  NOT NULL,
    loc                         character varying(3)   NOT NULL,
    whs                         character varying(3)   DEFAULT '00' NOT NULL,
    allow_ctrl_tot_view         character varying(1),
    allow_dl_rep_enq            character varying(1),
    allow_dl_opr_enq            character varying(1),
    allow_qt_maint              character varying(1),
    allow_qt_enq                character varying(1),
    allow_so_maint              character varying(1),
    allow_so_enq                character varying(1),
    allow_del_maint             character varying(1),
    allow_inv_maint             character varying(1),
    allow_inv_enq               character varying(1),
    allow_po_maint              character varying(1),
    allow_po_enq                character varying(1),
    allow_grn_maint             character varying(1),
    allow_grn_enq               character varying(1),
    allow_ibr_maint             character varying(1),
    allow_ib_maint              character varying(1),
    allow_stk_adjustments_whs   character varying(1),
    allow_stk_detailed_enq      character varying(1),
    allow_stk_warehouse_view    character varying(1)   DEFAULT 'N',
    CONSTRAINT sy02l_pk PRIMARY KEY (user_name, loc, whs)
);

CREATE TABLE IF NOT EXISTS public.sy35_chg_log (
    log_id                      SERIAL                 PRIMARY KEY,
    tbl_name                    character varying(40),
    key_field                   character varying(100),
    field_name                  character varying(40),
    old_value                   text,
    new_value                   text,
    changed_by                  character varying(20),
    changed_at                  timestamp              DEFAULT NOW()
);

-- ── Partner Portal tables ─────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS pp_partners (
    id              SERIAL       PRIMARY KEY,
    company_name    VARCHAR(100) NOT NULL,
    contact_name    VARCHAR(80)  NOT NULL,
    email           VARCHAR(100) NOT NULL UNIQUE,
    phone           VARCHAR(30),
    password_hash   VARCHAR(255) NOT NULL,
    role            VARCHAR(20)  NOT NULL DEFAULT 'PARTNER',
    active          BOOLEAN      DEFAULT TRUE,
    created_at      TIMESTAMP    DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS pp_registrations (
    id              SERIAL       PRIMARY KEY,
    partner_id      INTEGER      NOT NULL REFERENCES pp_partners(id),
    package_type    VARCHAR(10)  NOT NULL,
    num_users       INTEGER      NOT NULL DEFAULT 1,
    standalone      BOOLEAN      DEFAULT TRUE,
    master_company  VARCHAR(100),
    sync_modules    VARCHAR(100),
    company_name    VARCHAR(100) NOT NULL,
    master_or_slave VARCHAR(10)  DEFAULT 'MASTER',
    postal_addr1    VARCHAR(60),  postal_addr2 VARCHAR(60),
    postal_addr3    VARCHAR(60),  postal_addr4 VARCHAR(60),
    physical_addr1  VARCHAR(60),  physical_addr2 VARCHAR(60),
    physical_addr3  VARCHAR(60),  physical_addr4 VARCHAR(60),
    telephone       VARCHAR(30),  fax          VARCHAR(30),
    company_email   VARCHAR(100), company_domain VARCHAR(100),
    reg_number      VARCHAR(30),  vat_number   VARCHAR(30),
    year_end_month  INTEGER,      vat_rate     NUMERIC(5,2) DEFAULT 15,
    bank_name       VARCHAR(60),  bank_branch  VARCHAR(60),
    bank_branch_code VARCHAR(20), bank_account VARCHAR(30),
    multi_currency  BOOLEAN      DEFAULT FALSE,
    local_currency  VARCHAR(40),  currency_code VARCHAR(6),
    period_gl       INTEGER,      period_cb    INTEGER,
    period_dl       INTEGER,      period_sa    INTEGER,
    period_cl       INTEGER,      period_pu    INTEGER,
    system_year_end INTEGER,
    status          VARCHAR(40)  NOT NULL DEFAULT 'DRAFT',
    decline_reason  TEXT,
    submitted_at    TIMESTAMP,
    created_at      TIMESTAMP    DEFAULT NOW(),
    updated_at      TIMESTAMP    DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS pp_reg_locations (
    id                  SERIAL   PRIMARY KEY,
    registration_id     INTEGER  NOT NULL REFERENCES pp_registrations(id) ON DELETE CASCADE,
    loc                 VARCHAR(3),  whs VARCHAR(3),
    loc_name            VARCHAR(60), region VARCHAR(40),
    stock_loc           BOOLEAN  DEFAULT FALSE,
    physical_addr1      VARCHAR(60), physical_addr2 VARCHAR(60),
    physical_addr3      VARCHAR(60), physical_addr4 VARCHAR(60)
);

CREATE TABLE IF NOT EXISTS pp_reg_users (
    id                  SERIAL   PRIMARY KEY,
    registration_id     INTEGER  NOT NULL REFERENCES pp_registrations(id) ON DELETE CASCADE,
    username            VARCHAR(30),  full_name   VARCHAR(80),
    email               VARCHAR(100), default_loc VARCHAR(3),
    access_grp          VARCHAR(10)
);

CREATE TABLE IF NOT EXISTS pp_workflow_events (
    id                  SERIAL   PRIMARY KEY,
    registration_id     INTEGER  NOT NULL REFERENCES pp_registrations(id),
    actor_id            INTEGER  REFERENCES pp_partners(id),
    actor_name          VARCHAR(80),
    event_type          VARCHAR(40) NOT NULL,
    from_status         VARCHAR(40), to_status VARCHAR(40),
    comments            TEXT,
    created_at          TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS pp_conversion_jobs (
    id                  SERIAL   PRIMARY KEY,
    registration_id     INTEGER  NOT NULL REFERENCES pp_registrations(id),
    status              VARCHAR(20) DEFAULT 'PENDING',
    started_at          TIMESTAMP, completed_at TIMESTAMP,
    log_output          TEXT,
    created_at          TIMESTAMP DEFAULT NOW()
);

-- Seed demo portal users (password = 'password123' via BCrypt)
INSERT INTO pp_partners (company_name, contact_name, email, password_hash, role)
VALUES
  ('Acme Resellers (Pty) Ltd','Anele Bhengu',   'partner@acme.co.za',  '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LjZeUEHSQ0y','PARTNER'),
  ('XactERP Operations',      'Admin User',      'admin@xacterp.co.za', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LjZeUEHSQ0y','XACT_ADMIN'),
  ('Imply (Pty) Ltd',         'Imply Approver',  'approver@imply.co.za','$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LjZeUEHSQ0y','IMPLY')
ON CONFLICT (email) DO NOTHING;
